default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  database: <%= ENV.fetch("POSTGRES_DATABASE") { "" } %>
  pool:     <%= ENV.fetch("POSTGRES_POOL") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") { "" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>

development:
  <<: *default

test:
  <<: *default
  database: "widgets_test"

staging:
  <<: *default

production:
  <<: *default
